In [6]:
import pandas as pd

In [7]:
#Load dataset
df = pd.read_excel("../data/data1.xlsx")

#Create a copy to preserve original dataset
clean_df = df.copy()

# Data collection and Understanding

In [8]:

df.head() #First 5 rows of the dataset

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [9]:
display(df.shape) #Dataset shape

display(df.info()) #information about dataset

(1200, 14)

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 131.4 KB

None

In [10]:

display(df.dtypes) #type of dataset

OrderID                       str
Date               datetime64[us]
CustomerID                    str
Product                       str
Quantity                    int64
UnitPrice                 float64
ShippingAddress               str
PaymentMethod                 str
OrderStatus                   str
TrackingNumber                str
ItemsInCart                 int64
CouponCode                    str
ReferralSource                str
TotalPrice                float64
dtype: object

In [11]:
display(df.duplicated().sum()) #check for duplicate values in the dataset

display(df.describe()) #statistical summary of the dataset

np.int64(0)

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

In [12]:
display(df["OrderStatus"].value_counts()) #count of unique values in the OrderStatus column
display(df["OrderStatus"].value_counts(normalize=True)) #percentage of unique values in the OrderStatus column

OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64

OrderStatus
Cancelled    0.208333
Returned     0.205833
Pending      0.197500
Shipped      0.195833
Delivered    0.192500
Name: proportion, dtype: float64

# Data Cleaning and Processing

In [13]:
# Handling Missing Values
missing_columns = clean_df.columns[clean_df.isnull().any()]

if not missing_columns.empty:
    print("Columns with missing values:\n", missing_columns.tolist())
else:
    print("No missing values in all the columns")

clean_df["CouponCode"] = clean_df["CouponCode"].fillna("No Coupon")
print(f"Missing Values handled")

Columns with missing values:
 ['CouponCode']
Missing Values handled

In [14]:
#  Standardize Text Columns
text_columns = [
    'Product',
    'PaymentMethod',
    'OrderStatus',
    'ReferralSource',
    'CouponCode'
]

for col in text_columns:
    clean_df[col] = clean_df[col].astype(str).str.strip()

In [15]:
# Save Cleaned Dataset
clean_df.to_csv(
    '../data/cleaned_ecommerce_dataset.csv',
    index=False
)